#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef IDWALLTOOLKIT_SWIFT_H
#define IDWALLTOOLKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <IDwallToolkit/IDwallToolkit.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IDwallToolkit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif




typedef SWIFT_ENUM(NSInteger, IDWallSend, open) {
  IDWallSendDocument = 0,
  IDWallSendFace = 1,
  IDWallSendAll = 2,
  IDWallSendPOA = 3,
  IDWallSendTypified = 4,
};

@class UIColor;

SWIFT_PROTOCOL("_TtP13IDwallToolkit17IDwallColorScheme_")
@protocol IDwallColorScheme
- (UIColor * _Nonnull)sdkPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkSecundary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkTertiary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkQuaternary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkBackground SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkNavigationBar SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)textPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)textSecundary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)textTerciary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)buttonText SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)successPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)successSecundary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)warningPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)shadowPrimary SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13IDwallToolkit17IDwallCoordinator")
@interface IDwallCoordinator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IDwallToolkit29IDwallCompleteFlowCoordinator")
@interface IDwallCompleteFlowCoordinator : IDwallCoordinator
- (void)startCompleteFlowWithDocument:(IDwallDocumentType)type forResult:(IDwallToolkitFlowResult _Nullable)callback;
- (void)startDocumentFlowWithDocument:(IDwallDocumentType)type forResult:(IDwallToolkitFlowResult _Nullable)callback;
- (void)startLivenessFlowForResult:(IDwallToolkitFlowResult _Nullable)callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13IDwallToolkit14IDwallDocument")
@interface IDwallDocument : IDwallCoordinator
- (void)presentNextStep;
- (void)presentPreviousStep;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

@interface IDwallDocument (SWIFT_EXTENSION(IDwallToolkit))
+ (IDwallDocument * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)request:(IDwallDocumentType)documentType andDocSide:(IDwallDocumentSide)documentSide andCallback:(IDwallToolkitImageResult _Nullable)callback;
- (void)presentTutorial:(BOOL)presentTutorial SWIFT_DEPRECATED_MSG("Use IDwallToolkitSettings.sharedInstance().setDocumentTutorialEnabled instead");
- (void)sendDataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
- (void)sendTypifiedDocumentDataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
- (void)sendPOADataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
@end

@class NSCoder;
@class UITraitCollection;

SWIFT_CLASS("_TtC13IDwallToolkit22IDwallDocumentTypeCard")
@interface IDwallDocumentTypeCard : UIView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end


@class NSString;

SWIFT_CLASS("_TtC13IDwallToolkit11IDwallEvent")
@interface IDwallEvent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary * _Nonnull properties;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol IDwallEventsHandler;

SWIFT_CLASS("_TtC13IDwallToolkit18IDwallEventManager")
@interface IDwallEventManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) IDwallEventManager * _Nonnull shared;)
+ (IDwallEventManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(IDwallEventManager * _Nonnull)value;
@property (nonatomic, strong) id <IDwallEventsHandler> _Nullable handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13IDwallToolkit19IDwallEventsHandler_")
@protocol IDwallEventsHandler
- (void)onEvent:(IDwallEvent * _Nonnull)event;
@end


SWIFT_CLASS("_TtC13IDwallToolkit10IDwallFace")
@interface IDwallFace : IDwallCoordinator
- (void)presentNextStep;
- (void)presentPreviousStep;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface IDwallFace (SWIFT_EXTENSION(IDwallToolkit))
+ (IDwallFace * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)request:(IDwallToolkitImageResult _Nullable)callback;
- (void)presentTutorial:(BOOL)presentTutorial SWIFT_DEPRECATED_MSG("Use IDwallToolkitSettings.sharedInstance().setLivenessTutorialEnabled instead");
- (void)faceFallbackActivated:(BOOL)flag;
- (void)sendDataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
@end

@class UIImage;
@class NSMutableArray;

SWIFT_PROTOCOL("_TtP13IDwallToolkit24IDwallRepositoryProtocol_")
@protocol IDwallRepositoryProtocol
+ (id <IDwallRepositoryProtocol> _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) CGFloat progress;
- (void)setDocumentFrontImage:(UIImage * _Nonnull)document;
- (void)setDocumentBackImage:(UIImage * _Nonnull)document;
- (void)setFaceImages:(NSMutableArray * _Nonnull)faceImages;
- (void)setFaceSmileImages:(NSMutableArray * _Nonnull)faceSmileImages;
- (void)setAuthKey:(NSString * _Nonnull)authKey;
- (BOOL)hasAuthKey SWIFT_WARN_UNUSED_RESULT;
- (void)setPublicKeys:(NSArray<NSString *> * _Nonnull)publicKeys;
- (void)setDocumentType:(IDwallDocumentType)documentType;
- (void)resetAllImages;
- (void)resetDocumentImages;
- (void)resetDocumentFront;
- (void)resetDocumentBack;
- (void)resetFaceImages;
- (UIImage * _Nullable)getDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasAllDocument SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getProgress SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceImages SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceSmileImagess SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getDocumentType SWIFT_WARN_UNUSED_RESULT;
- (void)sendDataWithDataType:(enum IDWallSend)dataType andCallBack:(IDwallToolkitSendResult _Nonnull)callback;
- (NSString * _Nullable)getAuthKey SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)getPublicKeys SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13IDwallToolkit16IDwallRepository")
@interface IDwallRepository : NSObject <IDwallRepositoryProtocol>
@property (nonatomic) CGFloat progress;
+ (id <IDwallRepositoryProtocol> _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)setDocumentFrontImage:(UIImage * _Nonnull)document;
- (void)setDocumentBackImage:(UIImage * _Nonnull)document;
- (void)setFaceImages:(NSMutableArray * _Nonnull)faceImages;
- (void)setFaceSmileImages:(NSMutableArray * _Nonnull)faceSmileImages;
- (void)setAuthKey:(NSString * _Nonnull)authKey;
- (void)setPublicKeys:(NSArray<NSString *> * _Nonnull)publicKeys;
- (BOOL)hasAuthKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getAuthKey SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)getPublicKeys SWIFT_WARN_UNUSED_RESULT;
- (void)setDocumentType:(IDwallDocumentType)documentType;
- (NSUInteger)getDocumentType SWIFT_WARN_UNUSED_RESULT;
- (void)resetAllImages;
- (void)resetDocumentImages;
- (void)resetDocumentFront;
- (void)resetDocumentBack;
- (void)resetFaceImages;
- (UIImage * _Nullable)getDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasAllDocument SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getProgress SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceImages SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceSmileImagess SWIFT_WARN_UNUSED_RESULT;
- (void)sendDataWithDataType:(enum IDWallSend)dataType andCallBack:(IDwallToolkitSendResult _Nonnull)callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13IDwallToolkit21IDwallToolkitSettings")
@interface IDwallToolkitSettings : NSObject
+ (IDwallToolkitSettings * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (BOOL)initWithAuthKey:(NSString * _Nonnull)authKey SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)setupIDWallPublicKey:(NSArray<NSString *> * _Nonnull)publicKeys;
- (void)setEventHandler:(id <IDwallEventsHandler> _Nonnull)handler;
- (void)setColorScheme:(id <IDwallColorScheme> _Nonnull)colorScheme;
- (void)faceFallbackActivated:(BOOL)flag;
- (void)setLoggingLevel:(LoggingLevel)level;
- (void)setCameraMockedImage:(UIImage * _Nonnull)image;
- (void)setDocumentTutorialEnabled:(BOOL)isEnabled;
- (void)setLivenessTutorialEnabled:(BOOL)isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IDwallToolkit9IqConfigs")
@interface IqConfigs : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull configs_version;
@property (nonatomic, copy) NSString * _Nonnull document_type;
@property (nonatomic) NSInteger document_detection_method;
@property (nonatomic) float geom_doc_max_corner_delta;
@property (nonatomic) float geom_doc_max_delta;
@property (nonatomic) float geom_doc_mean_ratio;
@property (nonatomic) float geom_image_border_exclude;
@property (nonatomic) float geom_image_margins;
@property (nonatomic) float geom_image_max_side;
@property (nonatomic) float geom_image_min_side;
@property (nonatomic) float light_max_mean_threshold;
@property (nonatomic) float light_min_mean_threshold;
@property (nonatomic) float reflex_doc_margins;
@property (nonatomic) float reflex_min_area;
@property (nonatomic) float reflex_threshold;
@property (nonatomic) float sharp_threshold;
@end


SWIFT_CLASS("_TtC13IDwallToolkit8IqResult")
@interface IqResult : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) NSInteger config_document_detection_method;
@property (nonatomic, copy) NSString * _Nonnull config_document_type;
@property (nonatomic, copy) NSString * _Nonnull version_platform;
@property (nonatomic) NSInteger all_bin_flags;
@property (nonatomic) double analysis_geometry;
@property (nonatomic) double analysis_lightness;
@property (nonatomic) double analysis_reflection;
@property (nonatomic) double analysis_sharpness;
@property (nonatomic) double config_geom_doc_max_corner_delta;
@property (nonatomic) double config_geom_doc_max_delta;
@property (nonatomic) double config_geom_doc_mean_ratio;
@property (nonatomic) double config_geom_image_border_exclude;
@property (nonatomic) double config_geom_image_margins;
@property (nonatomic) double config_geom_image_max_side;
@property (nonatomic) double config_geom_image_min_side;
@property (nonatomic) double config_light_max_mean_threshold;
@property (nonatomic) double config_light_min_mean_threshold;
@property (nonatomic) double config_reflex_doc_margins;
@property (nonatomic) double config_reflex_min_area;
@property (nonatomic) double config_reflex_threshold;
@property (nonatomic) double config_sharp_threshold;
@property (nonatomic) NSInteger statistic_img_cols;
@property (nonatomic) NSInteger statistic_img_rows;
@property (nonatomic) NSInteger statistic_n_frames;
@property (nonatomic) NSInteger statistic_n_frames_ok;
@property (nonatomic) NSInteger statistic_n_frames_ok_ma;
@property (nonatomic) NSInteger statistic_n_locked_calls;
@property (nonatomic) NSInteger statistic_n_zero_images;
@property (nonatomic) BOOL flag_all_is_ok;
@property (nonatomic) BOOL flag_image_geometry_fails;
@property (nonatomic) BOOL flag_image_lightness_fails;
@property (nonatomic) BOOL flag_image_reflections_fails;
@property (nonatomic) BOOL flag_image_sharpness_fails;
@property (nonatomic) BOOL flag_document_is_small;
@property (nonatomic) BOOL flag_document_ratio_fails;
@property (nonatomic) BOOL flag_this_is_better;
@property (nonatomic) BOOL flag_this_is_big;
@property (nonatomic) BOOL flag_this_is_small;
@property (nonatomic) BOOL flag_this_is_too_bright;
@property (nonatomic) BOOL flag_this_is_too_dark;
@end
















#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef IDWALLTOOLKIT_SWIFT_H
#define IDWALLTOOLKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#import <IDwallToolkit/IDwallToolkit.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IDwallToolkit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif




typedef SWIFT_ENUM(NSInteger, IDWallSend, open) {
  IDWallSendDocument = 0,
  IDWallSendFace = 1,
  IDWallSendAll = 2,
  IDWallSendPOA = 3,
  IDWallSendTypified = 4,
};

@class UIColor;

SWIFT_PROTOCOL("_TtP13IDwallToolkit17IDwallColorScheme_")
@protocol IDwallColorScheme
- (UIColor * _Nonnull)sdkPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkSecundary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkTertiary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkQuaternary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkBackground SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)sdkNavigationBar SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)textPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)textSecundary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)textTerciary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)buttonText SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)successPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)successSecundary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)warningPrimary SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)shadowPrimary SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13IDwallToolkit17IDwallCoordinator")
@interface IDwallCoordinator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IDwallToolkit29IDwallCompleteFlowCoordinator")
@interface IDwallCompleteFlowCoordinator : IDwallCoordinator
- (void)startCompleteFlowWithDocument:(IDwallDocumentType)type forResult:(IDwallToolkitFlowResult _Nullable)callback;
- (void)startDocumentFlowWithDocument:(IDwallDocumentType)type forResult:(IDwallToolkitFlowResult _Nullable)callback;
- (void)startLivenessFlowForResult:(IDwallToolkitFlowResult _Nullable)callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13IDwallToolkit14IDwallDocument")
@interface IDwallDocument : IDwallCoordinator
- (void)presentNextStep;
- (void)presentPreviousStep;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

@interface IDwallDocument (SWIFT_EXTENSION(IDwallToolkit))
+ (IDwallDocument * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)request:(IDwallDocumentType)documentType andDocSide:(IDwallDocumentSide)documentSide andCallback:(IDwallToolkitImageResult _Nullable)callback;
- (void)presentTutorial:(BOOL)presentTutorial SWIFT_DEPRECATED_MSG("Use IDwallToolkitSettings.sharedInstance().setDocumentTutorialEnabled instead");
- (void)sendDataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
- (void)sendTypifiedDocumentDataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
- (void)sendPOADataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
@end

@class NSCoder;
@class UITraitCollection;

SWIFT_CLASS("_TtC13IDwallToolkit22IDwallDocumentTypeCard")
@interface IDwallDocumentTypeCard : UIView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end


@class NSString;

SWIFT_CLASS("_TtC13IDwallToolkit11IDwallEvent")
@interface IDwallEvent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary * _Nonnull properties;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol IDwallEventsHandler;

SWIFT_CLASS("_TtC13IDwallToolkit18IDwallEventManager")
@interface IDwallEventManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) IDwallEventManager * _Nonnull shared;)
+ (IDwallEventManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(IDwallEventManager * _Nonnull)value;
@property (nonatomic, strong) id <IDwallEventsHandler> _Nullable handler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13IDwallToolkit19IDwallEventsHandler_")
@protocol IDwallEventsHandler
- (void)onEvent:(IDwallEvent * _Nonnull)event;
@end


SWIFT_CLASS("_TtC13IDwallToolkit10IDwallFace")
@interface IDwallFace : IDwallCoordinator
- (void)presentNextStep;
- (void)presentPreviousStep;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface IDwallFace (SWIFT_EXTENSION(IDwallToolkit))
+ (IDwallFace * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)request:(IDwallToolkitImageResult _Nullable)callback;
- (void)presentTutorial:(BOOL)presentTutorial SWIFT_DEPRECATED_MSG("Use IDwallToolkitSettings.sharedInstance().setLivenessTutorialEnabled instead");
- (void)faceFallbackActivated:(BOOL)flag;
- (void)sendDataWithCallback:(IDwallToolkitSendResult _Nullable)callback;
@end

@class UIImage;
@class NSMutableArray;

SWIFT_PROTOCOL("_TtP13IDwallToolkit24IDwallRepositoryProtocol_")
@protocol IDwallRepositoryProtocol
+ (id <IDwallRepositoryProtocol> _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) CGFloat progress;
- (void)setDocumentFrontImage:(UIImage * _Nonnull)document;
- (void)setDocumentBackImage:(UIImage * _Nonnull)document;
- (void)setFaceImages:(NSMutableArray * _Nonnull)faceImages;
- (void)setFaceSmileImages:(NSMutableArray * _Nonnull)faceSmileImages;
- (void)setAuthKey:(NSString * _Nonnull)authKey;
- (BOOL)hasAuthKey SWIFT_WARN_UNUSED_RESULT;
- (void)setPublicKeys:(NSArray<NSString *> * _Nonnull)publicKeys;
- (void)setDocumentType:(IDwallDocumentType)documentType;
- (void)resetAllImages;
- (void)resetDocumentImages;
- (void)resetDocumentFront;
- (void)resetDocumentBack;
- (void)resetFaceImages;
- (UIImage * _Nullable)getDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasAllDocument SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getProgress SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceImages SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceSmileImagess SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)getDocumentType SWIFT_WARN_UNUSED_RESULT;
- (void)sendDataWithDataType:(enum IDWallSend)dataType andCallBack:(IDwallToolkitSendResult _Nonnull)callback;
- (NSString * _Nullable)getAuthKey SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)getPublicKeys SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13IDwallToolkit16IDwallRepository")
@interface IDwallRepository : NSObject <IDwallRepositoryProtocol>
@property (nonatomic) CGFloat progress;
+ (id <IDwallRepositoryProtocol> _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)setDocumentFrontImage:(UIImage * _Nonnull)document;
- (void)setDocumentBackImage:(UIImage * _Nonnull)document;
- (void)setFaceImages:(NSMutableArray * _Nonnull)faceImages;
- (void)setFaceSmileImages:(NSMutableArray * _Nonnull)faceSmileImages;
- (void)setAuthKey:(NSString * _Nonnull)authKey;
- (void)setPublicKeys:(NSArray<NSString *> * _Nonnull)publicKeys;
- (BOOL)hasAuthKey SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getAuthKey SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)getPublicKeys SWIFT_WARN_UNUSED_RESULT;
- (void)setDocumentType:(IDwallDocumentType)documentType;
- (NSUInteger)getDocumentType SWIFT_WARN_UNUSED_RESULT;
- (void)resetAllImages;
- (void)resetDocumentImages;
- (void)resetDocumentFront;
- (void)resetDocumentBack;
- (void)resetFaceImages;
- (UIImage * _Nullable)getDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentFrontImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDocumentBackImage SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasAllDocument SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)getProgress SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceImages SWIFT_WARN_UNUSED_RESULT;
- (NSMutableArray * _Nullable)getFaceSmileImagess SWIFT_WARN_UNUSED_RESULT;
- (void)sendDataWithDataType:(enum IDWallSend)dataType andCallBack:(IDwallToolkitSendResult _Nonnull)callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13IDwallToolkit21IDwallToolkitSettings")
@interface IDwallToolkitSettings : NSObject
+ (IDwallToolkitSettings * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (BOOL)initWithAuthKey:(NSString * _Nonnull)authKey SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)setupIDWallPublicKey:(NSArray<NSString *> * _Nonnull)publicKeys;
- (void)setEventHandler:(id <IDwallEventsHandler> _Nonnull)handler;
- (void)setColorScheme:(id <IDwallColorScheme> _Nonnull)colorScheme;
- (void)faceFallbackActivated:(BOOL)flag;
- (void)setLoggingLevel:(LoggingLevel)level;
- (void)setCameraMockedImage:(UIImage * _Nonnull)image;
- (void)setDocumentTutorialEnabled:(BOOL)isEnabled;
- (void)setLivenessTutorialEnabled:(BOOL)isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IDwallToolkit9IqConfigs")
@interface IqConfigs : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull configs_version;
@property (nonatomic, copy) NSString * _Nonnull document_type;
@property (nonatomic) NSInteger document_detection_method;
@property (nonatomic) float geom_doc_max_corner_delta;
@property (nonatomic) float geom_doc_max_delta;
@property (nonatomic) float geom_doc_mean_ratio;
@property (nonatomic) float geom_image_border_exclude;
@property (nonatomic) float geom_image_margins;
@property (nonatomic) float geom_image_max_side;
@property (nonatomic) float geom_image_min_side;
@property (nonatomic) float light_max_mean_threshold;
@property (nonatomic) float light_min_mean_threshold;
@property (nonatomic) float reflex_doc_margins;
@property (nonatomic) float reflex_min_area;
@property (nonatomic) float reflex_threshold;
@property (nonatomic) float sharp_threshold;
@end


SWIFT_CLASS("_TtC13IDwallToolkit8IqResult")
@interface IqResult : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) NSInteger config_document_detection_method;
@property (nonatomic, copy) NSString * _Nonnull config_document_type;
@property (nonatomic, copy) NSString * _Nonnull version_platform;
@property (nonatomic) NSInteger all_bin_flags;
@property (nonatomic) double analysis_geometry;
@property (nonatomic) double analysis_lightness;
@property (nonatomic) double analysis_reflection;
@property (nonatomic) double analysis_sharpness;
@property (nonatomic) double config_geom_doc_max_corner_delta;
@property (nonatomic) double config_geom_doc_max_delta;
@property (nonatomic) double config_geom_doc_mean_ratio;
@property (nonatomic) double config_geom_image_border_exclude;
@property (nonatomic) double config_geom_image_margins;
@property (nonatomic) double config_geom_image_max_side;
@property (nonatomic) double config_geom_image_min_side;
@property (nonatomic) double config_light_max_mean_threshold;
@property (nonatomic) double config_light_min_mean_threshold;
@property (nonatomic) double config_reflex_doc_margins;
@property (nonatomic) double config_reflex_min_area;
@property (nonatomic) double config_reflex_threshold;
@property (nonatomic) double config_sharp_threshold;
@property (nonatomic) NSInteger statistic_img_cols;
@property (nonatomic) NSInteger statistic_img_rows;
@property (nonatomic) NSInteger statistic_n_frames;
@property (nonatomic) NSInteger statistic_n_frames_ok;
@property (nonatomic) NSInteger statistic_n_frames_ok_ma;
@property (nonatomic) NSInteger statistic_n_locked_calls;
@property (nonatomic) NSInteger statistic_n_zero_images;
@property (nonatomic) BOOL flag_all_is_ok;
@property (nonatomic) BOOL flag_image_geometry_fails;
@property (nonatomic) BOOL flag_image_lightness_fails;
@property (nonatomic) BOOL flag_image_reflections_fails;
@property (nonatomic) BOOL flag_image_sharpness_fails;
@property (nonatomic) BOOL flag_document_is_small;
@property (nonatomic) BOOL flag_document_ratio_fails;
@property (nonatomic) BOOL flag_this_is_better;
@property (nonatomic) BOOL flag_this_is_big;
@property (nonatomic) BOOL flag_this_is_small;
@property (nonatomic) BOOL flag_this_is_too_bright;
@property (nonatomic) BOOL flag_this_is_too_dark;
@end
















#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
